### ISSUE TITLE
Ensure alignment for vortex-buffer

### ISSUE THREAD

**Issue by robert3005** [vortex-data/vortex#454] opened 2024-07-12 14:51 UTC
Right now when creating Bytes based buffers we lose the alignment information. There has been no movement on issue to allow this https://github.com/tokio-rs/bytes/issues/437 which would mean that unless allocator_api is stable this is unlikely to happen.

**Comment by gatesn** [comment] 2024-12-17 10:13
I came across an aligned-buffer and aligned-buffer-pool as part of the Rkyv utilities repo: https://crates.io/crates/aligned-buffer

I will try to rebuild vortex-buffer (along with mutable and P-typed versions) around this crate and then we can move away from Arrow buffers, Bytes buffers, `Vec<u8>` and `Vec<PType::NATIVE>`.

**Comment by gatesn** [comment] 2024-12-17 10:13
There is an open question though around how we handle unaligned buffers coming in from external systems.

**Comment by gatesn** [comment] 2024-12-17 17:22
Dupe of #115

**Closed as completed by gatesn** 2024-12-17 17:22 UTC
