### ISSUE TITLE
TakeFn::take should take an owned ArrayData of indices

### ISSUE THREAD

**Issue by danking** [vortex-data/vortex#1706] opened 2024-12-17 22:31 UTC
```rust
pub trait TakeFn<Array> {
    fn take(&self, array: &Array, indices: &ArrayData) -> VortexResult<ArrayData>;
    // ...
}
```

When the bit width of the indices matches the bit width of the array's data, we could re-use the memory of the indices for the result of this operation. This is only possible if the indices memory is uniquely owned which the reference argument prevents.

I propose `indices: ArrayData`. There are two cases:
- if the caller does not need indices anymore, then, when the bit widths match, we save an allocation.
- if the caller does need the indices, we pay for an Arc increment.

If the former is the common case, it seems clear there's a big savings.

**Comment by danking** [comment] 2024-12-17 22:32
cc: @lwwmanning

**Comment by lwwmanning** [comment] 2024-12-18 17:46
dupe of #1396

**Closed as completed by lwwmanning** 2024-12-18 17:46 UTC
